'use client';

import React, { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { RouteGuard } from '@/components/auth/RouteGuard';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { useAuth } from '@/hooks/use-auth';
import { Button } from '@/components/ui/Button';
import { DataTable } from '@/components/ui/DataTable';
import LoadingSpinner from '@/components/ui/LoadingSpinner';
import Pagination from '@/components/ui/Pagination';
import SearchFilter, { FilterOption } from '@/components/ui/SearchFilter';

interface Lead {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  status: 'new' | 'contacted' | 'qualified' | 'converted' | 'lost';
  conversionStage: 'lead' | 'application' | 'approval' | 'closing';
  priority: 'low' | 'medium' | 'high' | 'urgent';
  source: string;
  loanAmount?: number;
  creditScore?: number;
  leadQualityScore?: number;
  geographicLocation?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  lastContactDate?: string;
  contactCount: number;
}

interface OfficerInfo {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  isActive: boolean;
  slug: string;
}

export default function OfficerLeadsPage() {
  const params = useParams();
  const router = useRouter();
  const { accessToken } = useAuth();
  const [leads, setLeads] = useState<Lead[]>([]);
  const [officerInfo, setOfficerInfo] = useState<OfficerInfo | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  
  // Pagination and filtering state
  const [currentPage, setCurrentPage] = useState(1);
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [stageFilter, setStageFilter] = useState('');
  const [priorityFilter, setPriorityFilter] = useState('');
  
  const ITEMS_PER_PAGE = 10;
  const officerSlug = params.slug as string;

  // Filter options
  const statusOptions: FilterOption[] = [
    { value: 'new', label: 'New' },
    { value: 'contacted', label: 'Contacted' },
    { value: 'qualified', label: 'Qualified' },
    { value: 'converted', label: 'Converted' },
    { value: 'lost', label: 'Lost' }
  ];
  
  const stageOptions: FilterOption[] = [
    { value: 'lead', label: 'Lead' },
    { value: 'application', label: 'Application' },
    { value: 'approval', label: 'Approval' },
    { value: 'closing', label: 'Closing' }
  ];
  
  const priorityOptions: FilterOption[] = [
    { value: 'low', label: 'Low' },
    { value: 'medium', label: 'Medium' },
    { value: 'high', label: 'High' },
    { value: 'urgent', label: 'Urgent' }
  ];

  // Filtered and paginated leads
  const filteredLeads = leads.filter(lead => {
    const matchesSearch = !searchQuery || 
      `${lead.firstName} ${lead.lastName}`.toLowerCase().includes(searchQuery.toLowerCase()) ||
      lead.email.toLowerCase().includes(searchQuery.toLowerCase()) ||
      lead.phone?.includes(searchQuery);
    
    const matchesStatus = !statusFilter || lead.status === statusFilter;
    const matchesStage = !stageFilter || lead.conversionStage === stageFilter;
    const matchesPriority = !priorityFilter || lead.priority === priorityFilter;
    
    return matchesSearch && matchesStatus && matchesStage && matchesPriority;
  });

  const totalPages = Math.ceil(filteredLeads.length / ITEMS_PER_PAGE);
  const paginatedLeads = filteredLeads.slice(
    (currentPage - 1) * ITEMS_PER_PAGE,
    currentPage * ITEMS_PER_PAGE
  );

  // Breadcrumb items
  // Breadcrumb items are now automatically generated by useBreadcrumb hook
  useEffect(() => {
    if (accessToken && officerSlug) {
      fetchOfficerInfo();
      fetchLeads();
    }
  }, [accessToken, officerSlug]);

  // Reset to page 1 when filters change
  useEffect(() => {
    setCurrentPage(1);
  }, [searchQuery, statusFilter, stageFilter, priorityFilter]);

  const fetchOfficerInfo = async () => {
    try {
      const response = await fetch(`/api/officers/by-slug/${officerSlug}`, {
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
      });
      
      if (!response.ok) {
        throw new Error('Failed to fetch officer information');
      }

      const data = await response.json();
      setOfficerInfo(data.officer);
    } catch (err) {
      console.error('Error fetching officer info:', err);
      setError(err instanceof Error ? err.message : 'Failed to fetch officer information');
    }
  };

  const fetchLeads = async () => {
    try {
      setLoading(true);
      setError(null);

      if (!accessToken) {
        throw new Error('No access token available');
      }

      const response = await fetch(`/api/officers/by-slug/${officerSlug}/leads`, {
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
      });
      
      if (!response.ok) {
        throw new Error('Failed to fetch leads');
      }

      const data = await response.json();
      setLeads(data.leads || []);
    } catch (err) {
      console.error('Error fetching leads:', err);
      setError(err instanceof Error ? err.message : 'Failed to fetch leads');
    } finally {
      setLoading(false);
    }
  };

  const formatCurrency = (amount?: number) => {
    if (!amount) return 'N/A';
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const getStatusColor = (status: Lead['status']) => {
    switch (status) {
      case 'new': return 'bg-blue-100 text-blue-800';
      case 'contacted': return 'bg-yellow-100 text-yellow-800';
      case 'qualified': return 'bg-green-100 text-green-800';
      case 'converted': return 'bg-purple-100 text-purple-800';
      case 'lost': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const getStageColor = (stage: Lead['conversionStage']) => {
    switch (stage) {
      case 'lead': return 'bg-blue-100 text-blue-800';
      case 'application': return 'bg-yellow-100 text-yellow-800';
      case 'approval': return 'bg-green-100 text-green-800';
      case 'closing': return 'bg-purple-100 text-purple-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const getPriorityColor = (priority: Lead['priority']) => {
    switch (priority) {
      case 'low': return 'bg-gray-100 text-gray-800';
      case 'medium': return 'bg-blue-100 text-blue-800';
      case 'high': return 'bg-yellow-100 text-yellow-800';
      case 'urgent': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const handleClearFilters = () => {
    setSearchQuery('');
    setStatusFilter('');
    setStageFilter('');
    setPriorityFilter('');
  };

  const handlePageChange = (page: number) => {
    setCurrentPage(page);
  };

  const handleViewDetails = (lead: Lead) => {
    // Create a slug from the lead's name and ID for better UX
    const leadSlug = `${lead.firstName.toLowerCase()}-${lead.lastName.toLowerCase()}-${lead.id.slice(-8)}`;
    router.push(`/admin/loanofficers/${officerSlug}/leads/${leadSlug}`);
  };

  const columns = [
    {
      key: 'name',
      title: 'Name',
      render: (value: any, lead: Lead) => (
        <div>
          <div className="font-medium text-gray-900">{lead.firstName} {lead.lastName}</div>
          <div className="text-sm text-gray-500">{lead.email}</div>
          <div className="text-sm text-gray-500">{lead.phone}</div>
        </div>
      )
    },
    {
      key: 'source',
      title: 'Source',
      render: (value: any, lead: Lead) => (
        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
          {lead.source?.replace('_', ' ').toUpperCase() || 'Unknown'}
        </span>
      )
    },
    {
      key: 'status',
      title: 'Status',
      render: (value: any, lead: Lead) => (
        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusColor(lead.status)}`}>
          {lead.status.charAt(0).toUpperCase() + lead.status.slice(1)}
        </span>
      )
    },
    {
      key: 'conversionStage',
      title: 'Stage',
      render: (value: any, lead: Lead) => (
        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStageColor(lead.conversionStage)}`}>
          {lead.conversionStage.charAt(0).toUpperCase() + lead.conversionStage.slice(1)}
        </span>
      )
    },
    {
      key: 'priority',
      title: 'Priority',
      render: (value: any, lead: Lead) => (
        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getPriorityColor(lead.priority)}`}>
          {lead.priority.charAt(0).toUpperCase() + lead.priority.slice(1)}
        </span>
      )
    },
    {
      key: 'actions',
      title: 'Actions',
      render: (value: any, lead: Lead) => (
        <Button
          variant="primary"
          size="sm"
          onClick={() => handleViewDetails(lead)}
          className="border-0"
        >
          View Details
        </Button>
      )
    }
  ];

  if (loading) {
    return (
      <DashboardLayout>
        <div className="flex justify-center items-center min-h-[400px]">
          <LoadingSpinner size="lg" />
        </div>
      </DashboardLayout>
    );
  }

  if (error) {
    return (
      <DashboardLayout>
        <div className="bg-red-50 border border-red-200 rounded-md p-4">
          <h3 className="text-lg font-semibold text-red-600 mb-2">Error Loading Leads</h3>
          <p className="text-red-600 mb-4">{error}</p>
          <Button onClick={fetchLeads} variant="primary">
            Try Again
          </Button>
        </div>
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout 
      title={`${officerInfo ? `${officerInfo.firstName} ${officerInfo.lastName}` : 'Officer'} Leads`}
      subtitle={`Manage leads for ${officerInfo ? `${officerInfo.firstName} ${officerInfo.lastName}` : 'this officer'}`}
      showBreadcrumb={true}
        breadcrumbVariant="elevated"
        breadcrumbSize="md"
    >
      <div className="space-y-6">
        {/* Breadcrumb Navigation */}
        


        {/* Header with stats */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-200">
            <div className="text-2xl font-bold text-[#005b7c]">{filteredLeads.length}</div>
            <div className="text-sm text-gray-600">
              {searchQuery || statusFilter || stageFilter || priorityFilter ? 'Filtered' : 'Total'} Leads
            </div>
          </div>
          
          <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-200">
            <div className="text-2xl font-bold text-[#008eab]">
              {filteredLeads.filter(lead => lead.status === 'new').length}
            </div>
            <div className="text-sm text-gray-600">New Leads</div>
          </div>
          
          <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-200">
            <div className="text-2xl font-bold text-[#01bcc6]">
              {filteredLeads.filter(lead => lead.status === 'converted').length}
            </div>
            <div className="text-sm text-gray-600">Converted</div>
          </div>
          
          <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-200">
            <div className="text-2xl font-bold text-[#005b7c]">
              {filteredLeads.length > 0 ? Math.round((filteredLeads.filter(lead => lead.status === 'converted').length / filteredLeads.length) * 100) : 0}%
            </div>
            <div className="text-sm text-gray-600">Conversion Rate</div>
          </div>
        </div>

        {/* Search and Filter */}
        <SearchFilter
          searchValue={searchQuery}
          onSearchChange={setSearchQuery}
          filters={[
            {
              label: 'Status',
              key: 'status',
              value: statusFilter,
              options: statusOptions,
              onChange: setStatusFilter
            },
            {
              label: 'Stage',
              key: 'stage',
              value: stageFilter,
              options: stageOptions,
              onChange: setStageFilter
            },
            {
              label: 'Priority',
              key: 'priority',
              value: priorityFilter,
              options: priorityOptions,
              onChange: setPriorityFilter
            }
          ]}
          onClearFilters={handleClearFilters}
          placeholder="Search by name, email, or phone..."
          className="mb-6"
        />

        {/* Leads Table */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200">
          <div className="px-6 py-4 border-b border-gray-200">
            <h3 className="text-lg font-semibold text-gray-900">Leads</h3>
          </div>
          <div className="px-6 py-4">
            <DataTable
              data={paginatedLeads}
              columns={columns}
              loading={loading}
              emptyMessage="No leads found for this officer"
            />
          </div>
        </div>

        {/* Pagination */}
        <Pagination
          currentPage={currentPage}
          totalPages={totalPages}
          onPageChange={handlePageChange}
          pageSize={ITEMS_PER_PAGE}
          totalItems={filteredLeads.length}
          className="mt-6"
        />
      </div>
    </DashboardLayout>
  );
}
