#!/usr/bin/env tsx

// Load environment variables first
import { config } from 'dotenv';
config({ path: '.env.local' });

// Verify DATABASE_URL is loaded
if (!process.env.DATABASE_URL) {
  console.error('❌ DATABASE_URL not found in environment variables');
  console.log('Available env vars:', Object.keys(process.env).filter(k => k.includes('DATABASE')));
  process.exit(1);
}

console.log('✅ DATABASE_URL loaded:', process.env.DATABASE_URL?.substring(0, 20) + '...');

// Now import database modules
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { pgTable, uuid, text, jsonb, timestamp, index, boolean, integer, decimal } from 'drizzle-orm/pg-core';
import { eq, and } from 'drizzle-orm';

// Define schema inline to avoid import issues
const users = pgTable('users', {
  id: uuid('id').primaryKey(),
  email: text('email').notNull().unique(),
  firstName: text('first_name'),
  lastName: text('last_name'),
  phone: text('phone'),
  avatar: text('avatar'),
  role: text('role').notNull().default('employee'),
  isActive: boolean('is_active').default(true),
  deactivated: boolean('deactivated').default(false),
  inviteStatus: text('invite_status').default('pending'),
  inviteSentAt: timestamp('invite_sent_at'),
  inviteExpiresAt: timestamp('invite_expires_at'),
  inviteToken: text('invite_token'),
  lastLoginAt: timestamp('last_login_at'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

const companies = pgTable('companies', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  logo: text('logo'),
  website: text('website'),
  licenseNumber: text('license_number'),
  address: jsonb('address'),
  phone: text('phone'),
  email: text('email'),
  adminEmail: text('admin_email'),
  adminEmailVerified: boolean('admin_email_verified').default(false),
  adminUserId: uuid('admin_user_id'),
  inviteStatus: text('invite_status').default('pending'),
  inviteSentAt: timestamp('invite_sent_at'),
  inviteExpiresAt: timestamp('invite_expires_at'),
  inviteToken: text('invite_token'),
  subscription: text('subscription').default('basic'),
  subscriptionExpiresAt: timestamp('subscription_expires_at'),
  isActive: boolean('is_active').default(true),
  deactivated: boolean('deactivated').default(false),
  settings: jsonb('settings').default('{}'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

const userCompanies = pgTable('user_companies', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull(),
  companyId: uuid('company_id').notNull(),
  role: text('role').notNull().default('employee'),
  permissions: jsonb('permissions').default('[]'),
  isActive: boolean('is_active').default(true),
  joinedAt: timestamp('joined_at').defaultNow(),
});

const templates = pgTable('templates', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  description: text('description'),
  previewImage: text('preview_image'),
  isActive: boolean('is_active').default(true),
  isPremium: boolean('is_premium').default(false),
  colors: jsonb('colors').notNull().default('{}'),
  typography: jsonb('typography').notNull().default('{}'),
  content: jsonb('content').notNull().default('{}'),
  layout: jsonb('layout').notNull().default('{}'),
  advanced: jsonb('advanced').notNull().default('{}'),
  classes: jsonb('classes').notNull().default('{}'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

const pageSettings = pgTable('page_settings', {
  id: uuid('id').primaryKey().defaultRandom(),
  companyId: uuid('company_id').notNull(),
  officerId: uuid('officer_id').notNull(),
  templateId: uuid('template_id').notNull(),
  template: text('template').notNull(),
  settings: jsonb('settings').notNull().default('{}'),
  isPublished: boolean('is_published').default(false),
  publishedAt: timestamp('published_at'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

const pageSettingsVersions = pgTable('page_settings_versions', {
  id: uuid('id').primaryKey().defaultRandom(),
  pageSettingsId: uuid('page_settings_id').notNull(),
  companyId: uuid('company_id').notNull(),
  officerId: uuid('officer_id').notNull(),
  template: text('template').notNull(),
  settings: jsonb('settings').notNull(),
  version: text('version').notNull(),
  storagePath: text('storage_path'),
  isAutoGenerated: boolean('is_auto_generated').default(false),
  createdAt: timestamp('created_at').defaultNow(),
});

// Create database connection
const connectionString = process.env.DATABASE_URL!;
const client = postgres(connectionString, {
  max: 20,
  idle_timeout: 20,
  connect_timeout: 10,
  max_lifetime: 60 * 30,
});

const db = drizzle(client);

interface LoanOfficer {
  id: string;
  email: string;
  firstName: string | null;
  lastName: string | null;
  companyId: string;
  companyName: string;
}

interface Template {
  id: string;
  slug: string;
  name: string;
  colors: any;
  typography: any;
  content: any;
  layout: any;
  advanced: any;
  classes: any;
  layout_config?: any; // Layout configuration for different template layouts
}

async function getLoanOfficers(): Promise<LoanOfficer[]> {
  console.log('🔍 Fetching loan officers...');
  
  const result = await db
    .select({
      id: users.id,
      email: users.email,
      firstName: users.firstName,
      lastName: users.lastName,
      companyId: companies.id,
      companyName: companies.name,
    })
    .from(users)
    .innerJoin(userCompanies, eq(users.id, userCompanies.userId))
    .innerJoin(companies, eq(userCompanies.companyId, companies.id))
    .where(and(
      eq(userCompanies.role, 'employee'),
      eq(userCompanies.isActive, true),
      eq(companies.isActive, true),
      eq(users.isActive, true)
    ));

  console.log(`✅ Found ${result.length} loan officers`);
  return result;
}

async function getTemplates(): Promise<Template[]> {
  console.log('🔍 Fetching templates...');
  
  const result = await db
    .select()
    .from(templates)
    .where(eq(templates.isActive, true));

  console.log(`✅ Found ${result.length} active templates`);
  return result;
}

async function getExistingPageSettings(): Promise<string[]> {
  console.log('🔍 Checking existing page settings...');
  
  const result = await db
    .select({ officerId: pageSettings.officerId })
    .from(pageSettings);

  const officerIds = result.map(r => r.officerId);
  console.log(`✅ Found ${officerIds.length} existing page settings`);
  return officerIds;
}

async function createDefaultSettings(template: Template): Promise<any> {
  // Create default settings based on template structure
  return {
    colors: template.colors || {},
    typography: template.typography || {},
    content: template.content || {},
    layout: template.layout || {},
    advanced: template.advanced || {},
    classes: template.classes || {},
    // Add any custom overrides here
    customizations: {
      lastModified: new Date().toISOString(),
      version: '1.0.0',
      isCustomized: false
    }
  };
}

async function populatePageSettings() {
  try {
    console.log('🚀 Starting page settings population...');
    
    // Get all loan officers
    const loanOfficers = await getLoanOfficers();
    if (loanOfficers.length === 0) {
      console.log('⚠️ No loan officers found. Exiting.');
      return;
    }

    // Get all templates
    const templates = await getTemplates();
    if (templates.length === 0) {
      console.log('⚠️ No templates found. Exiting.');
      return;
    }

    // Get existing page settings to avoid duplicates
    const existingOfficerIds = await getExistingPageSettings();

    // Use the first template as default (you can change this logic)
    const defaultTemplate = templates[0];
    console.log(`📋 Using default template: ${defaultTemplate.name} (${defaultTemplate.slug})`);

    let createdCount = 0;
    let skippedCount = 0;

    for (const officer of loanOfficers) {
      // Skip if officer already has page settings
      if (existingOfficerIds.includes(officer.id)) {
        console.log(`⏭️ Skipping officer ${officer.email} - already has page settings`);
        skippedCount++;
        continue;
      }

      try {
        console.log(`📝 Creating page settings for officer: ${officer.email}`);
        
        // Create default settings
        const defaultSettings = await createDefaultSettings(defaultTemplate);
        
        // Insert page settings
        const [newPageSettings] = await db
          .insert(pageSettings)
          .values({
            companyId: officer.companyId,
            officerId: officer.id,
            templateId: defaultTemplate.id,
            template: defaultTemplate.slug,
            settings: defaultSettings,
            isPublished: false,
            publishedAt: null,
          })
          .returning();

        console.log(`✅ Created page settings for ${officer.email} (ID: ${newPageSettings.id})`);

        // Create initial version
        const [newVersion] = await db
          .insert(pageSettingsVersions)
          .values({
            pageSettingsId: newPageSettings.id,
            companyId: officer.companyId,
            officerId: officer.id,
            template: defaultTemplate.slug,
            settings: defaultSettings,
            version: '1.0.0',
            storagePath: null,
            isAutoGenerated: true,
          })
          .returning();

        console.log(`✅ Created initial version for ${officer.email} (Version ID: ${newVersion.id})`);
        createdCount++;

      } catch (error) {
        console.error(`❌ Error creating page settings for ${officer.email}:`, error);
      }
    }

    console.log('\n📊 Summary:');
    console.log(`✅ Created: ${createdCount} page settings`);
    console.log(`⏭️ Skipped: ${skippedCount} officers (already have settings)`);
    console.log(`📋 Total officers processed: ${loanOfficers.length}`);

  } catch (error) {
    console.error('❌ Error in populatePageSettings:', error);
    throw error;
  }
}

async function main() {
  try {
    await populatePageSettings();
    console.log('\n🎉 Page settings population completed successfully!');
  } catch (error) {
    console.error('💥 Script failed:', error);
    process.exit(1);
  } finally {
    process.exit(0);
  }
}

// Run the script
if (require.main === module) {
  main();
}

export { populatePageSettings };
