'use client';

import React, { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { Button } from '@/components/ui/Button';
import SpotlightCard from '@/components/ui/SpotlightCard';
import { useAuth } from '@/hooks/use-auth';
import { supabase } from '@/lib/supabase/client';
import { typography, colors, spacing, borderRadius } from '@/theme/theme';
import { icons } from '@/components/ui/Icon';
import Loader from '@/components/ui/Loader';
import SmartDropdown, { SmartDropdownOption } from '@/components/ui/SmartDropdown';
import { useNotification } from '@/components/ui/Notification';
// Breadcrumb is now handled automatically by DashboardLayout

interface Lead {
  id: string;
  companyId: string;
  officerId: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  status: 'new' | 'contacted' | 'qualified' | 'converted' | 'lost';
  conversionStage: 'lead' | 'application' | 'approval' | 'closing';
  priority: 'low' | 'medium' | 'high' | 'urgent';
  source: string;
  loanAmount?: number;
  loanAmountClosed?: number;
  commissionEarned?: number;
  downPayment?: number;
  creditScore?: number;
  responseTimeHours?: number;
  leadQualityScore?: number;
  geographicLocation?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  lastContactDate?: string;
  contactCount: number;
  conversionDate?: string;
  applicationDate?: string;
  approvalDate?: string;
  closingDate?: string;
  tags?: string[];
  customFields?: Record<string, any>;
  propertyDetails?: Record<string, any>;
  loanDetails?: {
    productId: string;
    lenderName: string;
    loanProgram: string;
    loanType: string;
    loanTerm: number;
    interestRate: number;
    apr: number;
    monthlyPayment: number;
    fees: number;
    points: number;
    credits: number;
    lockPeriod: number;
  };
}

const STATUS_OPTIONS: SmartDropdownOption[] = [
  { value: 'new', label: 'New', icon: 'plus' },
  { value: 'contacted', label: 'Contacted', icon: 'phone' },
  { value: 'qualified', label: 'Qualified', icon: 'checkCircle' },
  { value: 'converted', label: 'Converted', icon: 'success' },
  { value: 'lost', label: 'Lost', icon: 'error' },
];

const STAGE_OPTIONS: SmartDropdownOption[] = [
  { value: 'lead', label: 'Lead', icon: 'target' },
  { value: 'application', label: 'Application', icon: 'document' },
  { value: 'approval', label: 'Approval', icon: 'checkCircle' },
  { value: 'closing', label: 'Closing', icon: 'calendar' },
];

const PRIORITY_OPTIONS: SmartDropdownOption[] = [
  { value: 'low', label: 'Low', icon: 'chevronsDown' },
  { value: 'medium', label: 'Medium', icon: 'filter' },
  { value: 'high', label: 'High', icon: 'chevronsUp' },
  { value: 'urgent', label: 'Urgent', icon: 'alertCircle' },
];

export default function LeadDetailsPage() {
  const params = useParams();
  const router = useRouter();
  const { user, accessToken } = useAuth();
  const { showNotification } = useNotification();
  const [lead, setLead] = useState<Lead | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  
  // Editing state
  const [editingField, setEditingField] = useState<string | null>(null);
  const [tempValue, setTempValue] = useState<string>('');
  const [saving, setSaving] = useState(false);

  const leadId = params.leadId as string;

  // Breadcrumb items are now automatically generated by useBreadcrumb hook

  useEffect(() => {
    if (accessToken && leadId) {
      fetchLeadDetails();
    }
  }, [accessToken, leadId]);

  const fetchLeadDetails = async () => {
    try {
      setLoading(true);
      setError(null);

      if (!accessToken) {
        throw new Error('No access token available');
      }

      const response = await fetch(`/api/leads/by-slug/${leadId}`, {
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
      });
      
      if (!response.ok) {
        throw new Error('Failed to fetch lead details');
      }

      const data = await response.json();
      setLead(data.lead);
    } catch (err) {
      console.error('Error fetching lead details:', err);
      setError(err instanceof Error ? err.message : 'Failed to fetch lead details');
    } finally {
      setLoading(false);
    }
  };

  const formatCurrency = (amount?: number) => {
    if (!amount) return 'N/A';
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const getStatusBadgeColor = (status: Lead['status']) => {
    switch (status) {
      case 'new': return 'bg-blue-100 text-blue-800';
      case 'contacted': return 'bg-yellow-100 text-yellow-800';
      case 'qualified': return 'bg-green-100 text-green-800';
      case 'converted': return 'bg-purple-100 text-purple-800';
      case 'lost': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const getStageBadgeColor = (stage: Lead['conversionStage']) => {
    switch (stage) {
      case 'lead': return 'bg-blue-100 text-blue-800';
      case 'application': return 'bg-yellow-100 text-yellow-800';
      case 'approval': return 'bg-green-100 text-green-800';
      case 'closing': return 'bg-purple-100 text-purple-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const getPriorityBadgeColor = (priority: Lead['priority']) => {
    switch (priority) {
      case 'low': return 'bg-gray-100 text-gray-800';
      case 'medium': return 'bg-blue-100 text-blue-800';
      case 'high': return 'bg-yellow-100 text-yellow-800';
      case 'urgent': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  // Editing functions
  const handleEditStart = (field: string, value: any) => {
    setEditingField(field);
    setTempValue(value?.toString() || '');
  };

  const handleEditCancel = () => {
    setEditingField(null);
    setTempValue('');
  };

  const handleUpdateField = async (field: keyof Lead, value: string) => {
    if (!lead || !accessToken || saving) return;

    try {
      setSaving(true);

      const { data: { session }, error: sessionError } = await supabase.auth.getSession();

      if (sessionError || !session?.access_token) {
        console.error('Session error:', sessionError);
        throw new Error('Authentication failed. Please refresh the page and try again.');
      }

      const response = await fetch(`/api/leads/${lead.id}/analytics`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session.access_token}`,
        },
        body: JSON.stringify({ [field]: value }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ error: 'Unknown error' }));
        console.error('API Error:', response.status, errorData);

        if (response.status === 401) {
          throw new Error('Authentication expired. Please refresh the page and try again.');
        } else if (response.status === 403) {
          throw new Error('You do not have permission to edit this lead.');
        } else if (response.status === 404) {
          throw new Error('Lead not found.');
        } else {
          throw new Error(`Failed to update lead: ${errorData.error || 'Unknown error'}`);
        }
      }

      await response.json();
      setLead(prevLead => prevLead ? { ...prevLead, [field]: value } : null);
      
      // Show success notification when leadQualityScore is updated
      if (field === 'leadQualityScore') {
        showNotification({
          type: 'success',
          title: 'Lead Quality Score Updated',
          message: `Lead quality score has been successfully updated to ${value}/10.`,
          duration: 3000,
        });
      }
    } catch (err) {
      console.error('Error updating lead:', err);
      const errorMessage = err instanceof Error ? err.message : 'Failed to update lead. Please try again.';
      alert(errorMessage);
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <DashboardLayout 
        showBreadcrumb={true}
        breadcrumbVariant="elevated"
        breadcrumbSize="md"
      >
        <div className="flex flex-col items-center justify-center text-gray-600">
          <Loader />
          Loading lead details...
        </div>
      </DashboardLayout>
    );
  }

  if (error) {
    return (
      <DashboardLayout 
        showBreadcrumb={true}
        breadcrumbVariant="elevated"
        breadcrumbSize="md"
      >
        <div style={{ padding: spacing[6] }}>
          <div style={{
            padding: spacing[6],
            backgroundColor: colors.red[50],
            border: `1px solid ${colors.red[200]}`,
            borderRadius: borderRadius.md,
            color: colors.red[600]
          }}>
            <h3 style={{ fontSize: typography.fontSize.lg, fontWeight: typography.fontWeight.semibold, marginBottom: spacing[2] }}>
              Error Loading Lead Details
            </h3>
            <p style={{ marginBottom: spacing[4] }}>{error}</p>
            <div className="flex gap-4">
              <Button onClick={fetchLeadDetails} variant="primary">
                Try Again
              </Button>
              <Button onClick={() => router.push('/officers/dashboard')} variant="secondary">
                Back to Dashboard
              </Button>
            </div>
          </div>
        </div>
      </DashboardLayout>
    );
  }

  if (!lead) {
    return (
      <DashboardLayout 
        showBreadcrumb={true}
        breadcrumbVariant="elevated"
        breadcrumbSize="md"
      >
        <div style={{ padding: spacing[6] }}>
          <div style={{
            padding: spacing[6],
            backgroundColor: colors.gray[50],
            border: `1px solid ${colors.gray[200]}`,
            borderRadius: borderRadius.md,
            color: colors.gray[600],
            textAlign: 'center'
          }}>
            <h3 style={{ fontSize: typography.fontSize.lg, fontWeight: typography.fontWeight.semibold, marginBottom: spacing[2] }}>
              Lead Not Found
            </h3>
            <p style={{ marginBottom: spacing[4] }}>The lead you're looking for doesn't exist or you don't have permission to view it.</p>
            <Button onClick={() => router.push('/officers/dashboard')} variant="primary">
              Back to Dashboard
            </Button>
          </div>
        </div>
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout 
      showBreadcrumb={true}
      breadcrumbVariant="elevated"
      breadcrumbSize="md"
    >
      <div style={{ padding: spacing[6] }}>
        {/* Header Actions */}
        <div className="flex justify-between items-center mb-8">
          
          <div className="flex gap-3">
            <SmartDropdown
              value={lead.status}
              onChange={(newValue) => handleUpdateField('status', newValue)}
              options={STATUS_OPTIONS}
              placeholder="Select status"
              buttonClassName="min-w-[160px]"
            />

            <SmartDropdown
              value={lead.conversionStage}
              onChange={(newValue) => handleUpdateField('conversionStage', newValue)}
              options={STAGE_OPTIONS}
              placeholder="Select stage"
              buttonClassName="min-w-[180px]"
            />

            <SmartDropdown
              value={lead.priority}
              onChange={(newValue) => handleUpdateField('priority', newValue)}
              options={PRIORITY_OPTIONS}
              placeholder="Select priority"
              buttonClassName="min-w-[150px]"
            />
          </div>
        </div>

        {/* Lead Details Grid - ALL Database Fields */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Contact & Basic Info */}
          <SpotlightCard variant="default" className="p-6 dashboard-card inner-page-card">
            <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
              {React.createElement(icons.user, { size: 20, className: "mr-2" })}
              Contact & Basic Information
            </h3>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Full Name</label>
                <p className="text-lg font-semibold text-gray-900">{lead.firstName} {lead.lastName}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>
                <p className="text-gray-900">{lead.email}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Phone</label>
                <p className="text-gray-900">{lead.phone || 'N/A'}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Source</label>
                <p className="text-gray-900">{lead.source || 'N/A'}</p>
              </div>
              {lead.geographicLocation && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Location</label>
                  <p className="text-gray-900">{lead.geographicLocation}</p>
                </div>
              )}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Created</label>
                <p className="text-gray-900">{formatDate(lead.createdAt)}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Last Updated</label>
                <p className="text-gray-900">{formatDate(lead.updatedAt)}</p>
              </div>
            </div>
          </SpotlightCard>

          {/* Financial Information */}
          <SpotlightCard variant="default" className="p-6 dashboard-card inner-page-card">
            <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
              {React.createElement(icons.dollarSign, { size: 20, className: "mr-2" })}
              Financial Information
            </h3>
            <div className="space-y-4">
              <div className="bg-gradient-to-r from-blue-50 to-indigo-50 p-4 rounded-md border border-blue-200 financial-highlight">
                <label className="block text-sm font-medium text-blue-700 mb-2">Requested Loan Amount</label>
                <p className="text-2xl font-bold text-blue-600">{formatCurrency(lead.loanAmount)}</p>
              </div>
              {lead.loanAmountClosed && (
                <div className="bg-gradient-to-r from-green-50 to-emerald-50 p-4 rounded-md border border-green-200">
                  <label className="block text-sm font-medium text-green-700 mb-2">Closed Loan Amount</label>
                  <p className="text-xl font-bold text-green-600">{formatCurrency(lead.loanAmountClosed)}</p>
                </div>
              )}
              {lead.commissionEarned && (
                <div className="bg-gradient-to-r from-purple-50 to-violet-50 p-4 rounded-md border border-purple-200">
                  <label className="block text-sm font-medium text-purple-700 mb-2">Commission Earned</label>
                  <p className="text-xl font-bold text-purple-600">{formatCurrency(lead.commissionEarned)}</p>
                </div>
              )}
              {lead.downPayment && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Down Payment</label>
                  <p className="text-gray-900">{formatCurrency(lead.downPayment)}</p>
                </div>
              )}
              {lead.creditScore && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Credit Score</label>
                  <p className="text-gray-900">{lead.creditScore}</p>
                </div>
              )}
            </div>
          </SpotlightCard>

          {/* Performance & Analytics */}
          <SpotlightCard variant="default" className="p-6 dashboard-card inner-page-card">
            <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
              {React.createElement(icons.trendingUp, { size: 20, className: "mr-2" })}
              Performance & Analytics
            </h3>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Lead Quality Score</label>
                {editingField === 'leadQualityScore' ? (
                  <div className="flex items-center">
                    <input
                      type="number"
                      min="1"
                      max="10"
                      value={tempValue}
                      onChange={(e) => setTempValue(e.target.value)}
                      className="w-16 text-sm border-2 border-blue-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 rounded-md px-3 py-2 mr-3 transition-all duration-200"
                      onBlur={() => handleUpdateField('leadQualityScore', tempValue)}
                      onKeyDown={(e) => {
                        if (e.key === 'Enter') handleUpdateField('leadQualityScore', tempValue);
                        if (e.key === 'Escape') handleEditCancel();
                      }}
                      autoFocus
                    />
                    <span className="text-sm text-gray-500">/10</span>
                  </div>
                ) : (
                  <div 
                    className="flex items-center cursor-pointer hover:opacity-80"
                    onClick={() => handleEditStart('leadQualityScore', lead.leadQualityScore || 5)}
                  >
                    <div className="flex-1 bg-gray-200 rounded-lg h-2 mr-3">
                      <div 
                        className="bg-blue-600 h-2 rounded-lg" 
                        style={{ width: `${((lead.leadQualityScore || 0) / 10) * 100}%` }}
                      ></div>
                    </div>
                    <span className="text-sm font-medium text-gray-900">{lead.leadQualityScore || 0}/10</span>
                  </div>
                )}
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Contact Count</label>
                <p className="text-gray-900">{lead.contactCount}</p>
              </div>
              {lead.responseTimeHours && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Response Time</label>
                  <p className="text-gray-900">{lead.responseTimeHours} hours</p>
                </div>
              )}
              {lead.lastContactDate && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Last Contact</label>
                  <p className="text-gray-900">{formatDate(lead.lastContactDate)}</p>
                </div>
              )}
            </div>
          </SpotlightCard>
        </div>

        {/* Conversion Timeline */}
        {lead.applicationDate||lead.approvalDate||lead.closingDate||lead.conversionDate &&
          (
            <SpotlightCard variant="default" className="mt-6 p-6 dashboard-card detail-card">
            <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
              {React.createElement(icons.clock, { size: 20, className: "mr-2" })}
              Conversion Timeline
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              {lead.conversionDate && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Conversion Date</label>
                  <p className="text-gray-900">{formatDate(lead.conversionDate)}</p>
                </div>
              )}
              {lead.applicationDate && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Application Date</label>
                  <p className="text-gray-900">{formatDate(lead.applicationDate)}</p>
                </div>
              )}
              {lead.approvalDate && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Approval Date</label>
                  <p className="text-gray-900">{formatDate(lead.approvalDate)}</p>
                </div>
              )}
              {lead.closingDate && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Closing Date</label>
                  <p className="text-gray-900">{formatDate(lead.closingDate)}</p>
                </div>
              )}
            </div>
          </SpotlightCard>
          )
        }



        {/* Loan Details - Simplified */}
        {lead.loanDetails && (
          <SpotlightCard variant="default" className="mt-6 p-6 dashboard-card detail-card">
            <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
              {React.createElement(icons.fileText, { size: 20, className: "mr-2" })}
              Loan Details
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Lender & Program</label>
                <p className="text-gray-900">{lead.loanDetails.lenderName} - {lead.loanDetails.loanProgram}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Loan Type & Term</label>
                <p className="text-gray-900">{lead.loanDetails.loanType} ({lead.loanDetails.loanTerm} years)</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Interest Rate & APR</label>
                <p className="text-gray-900">{lead.loanDetails.interestRate}% / {lead.loanDetails.apr}% APR</p>
              </div>
              <div className="bg-gradient-to-r from-blue-50 to-indigo-50 p-4 rounded-md border border-blue-200 financial-highlight">
                <label className="block text-sm font-medium text-blue-700 mb-2">Monthly Payment</label>
                <p className="text-2xl font-bold text-blue-600">{formatCurrency(lead.loanDetails.monthlyPayment)}</p>
              </div>
            </div>
          </SpotlightCard>
        )}

        {/* Notes - Editable */}
        <SpotlightCard variant="default" className="mt-6 p-6 dashboard-card detail-card">
          <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
            {React.createElement(icons.messageSquare, { size: 20, className: "mr-2" })}
            Notes
          </h3>
          {editingField === 'notes' ? (
            <textarea
              value={tempValue}
              onChange={(e) => setTempValue(e.target.value)}
              className="w-full text-sm border-2 border-blue-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 rounded-md px-4 py-3 transition-all duration-200 resize-none"
              rows={4}
              onBlur={() => handleUpdateField('notes', tempValue)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && e.ctrlKey) handleUpdateField('notes', tempValue);
                if (e.key === 'Escape') handleEditCancel();
              }}
              autoFocus
              placeholder="Add notes about this lead..."
            />
          ) : (
            <div 
              className="bg-gradient-to-r from-gray-50 to-slate-50 rounded-md p-6 cursor-pointer hover:from-gray-100 hover:to-slate-100 min-h-[80px] notes-section border border-gray-200 hover:border-gray-300 hover:shadow-md"
              onClick={() => handleEditStart('notes', lead.notes || '')}
            >
              <p className="text-gray-700 whitespace-pre-wrap leading-relaxed">{lead.notes || 'Click to add notes...'}</p>
            </div>
          )}
        </SpotlightCard>
      </div>
    </DashboardLayout>
  );
}
