'use client';

import React, { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { RouteGuard } from '@/components/auth/RouteGuard';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { useAuth } from '@/hooks/use-auth';
import { Button } from '@/components/ui/Button';
// Breadcrumb is now handled automatically by DashboardLayout

interface Lead {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  status: 'new' | 'contacted' | 'qualified' | 'converted' | 'lost';
  conversionStage: 'lead' | 'application' | 'approval' | 'closing';
  priority: 'low' | 'medium' | 'high' | 'urgent';
  source: string;
  loanAmount?: number;
  creditScore?: number;
  leadQualityScore?: number;
  geographicLocation?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  lastContactDate?: string;
  contactCount: number;
  loanAmountClosed?: number;
  commissionEarned?: number;
  responseTimeHours?: number;
}

interface OfficerInfo {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  isActive: boolean;
  slug: string;
}

export default function SuperAdminLeadDetailsPage() {
  const params = useParams();
  const router = useRouter();
  const { accessToken } = useAuth();
  const [lead, setLead] = useState<Lead | null>(null);
  const [officerInfo, setOfficerInfo] = useState<OfficerInfo | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  
  const officerSlug = params.slug as string;
  const leadSlug = params.leadSlug as string;

  // Breadcrumb items are now automatically generated by useBreadcrumb hook

  useEffect(() => {
    if (accessToken && officerSlug && leadSlug) {
      fetchOfficerInfo();
      fetchLeadDetails();
    }
  }, [accessToken, officerSlug, leadSlug]);

  const fetchOfficerInfo = async () => {
    try {
      const response = await fetch(`/api/officers/by-slug/${officerSlug}`, {
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
      });
      
      if (!response.ok) {
        throw new Error('Failed to fetch officer information');
      }

      const data = await response.json();
      setOfficerInfo(data.officer);
    } catch (err) {
      console.error('Error fetching officer info:', err);
    }
  };

  const fetchLeadDetails = async () => {
    try {
      setLoading(true);
      setError(null);

      if (!accessToken) {
        throw new Error('No access token available');
      }

      const response = await fetch(`/api/leads/by-slug/${leadSlug}`, {
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
      });
      
      if (!response.ok) {
        throw new Error('Failed to fetch lead details');
      }

      const data = await response.json();
      setLead(data.lead);
    } catch (err) {
      console.error('Error fetching lead details:', err);
      setError(err instanceof Error ? err.message : 'Failed to fetch lead details');
    } finally {
      setLoading(false);
    }
  };

  const formatCurrency = (amount?: number) => {
    if (!amount) return 'N/A';
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const getStatusColor = (status: Lead['status']) => {
    switch (status) {
      case 'new': return 'bg-blue-100 text-blue-800';
      case 'contacted': return 'bg-yellow-100 text-yellow-800';
      case 'qualified': return 'bg-green-100 text-green-800';
      case 'converted': return 'bg-purple-100 text-purple-800';
      case 'lost': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const getStageColor = (stage: Lead['conversionStage']) => {
    switch (stage) {
      case 'lead': return 'bg-blue-100 text-blue-800';
      case 'application': return 'bg-yellow-100 text-yellow-800';
      case 'approval': return 'bg-green-100 text-green-800';
      case 'closing': return 'bg-purple-100 text-purple-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const getPriorityColor = (priority: Lead['priority']) => {
    switch (priority) {
      case 'low': return 'bg-gray-100 text-gray-800';
      case 'medium': return 'bg-blue-100 text-blue-800';
      case 'high': return 'bg-yellow-100 text-yellow-800';
      case 'urgent': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  if (loading) {
    return (
      <DashboardLayout>
        <div className="flex justify-center items-center min-h-[400px]">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mr-4"></div>
          Loading lead details...
        </div>
      </DashboardLayout>
    );
  }

  if (error) {
    return (
      <DashboardLayout>
        <div className="bg-red-50 border border-red-200 rounded-md p-4">
          <h3 className="text-lg font-semibold text-red-600 mb-2">Error Loading Lead Details</h3>
          <p className="text-red-600 mb-4">{error}</p>
          <Button onClick={fetchLeadDetails} variant="primary">
            Try Again
          </Button>
        </div>
      </DashboardLayout>
    );
  }

  if (!lead) {
    return (
      <DashboardLayout>
        <div className="bg-yellow-50 border border-yellow-200 rounded-md p-4">
          <h3 className="text-lg font-semibold text-yellow-600 mb-2">Lead Not Found</h3>
          <p className="text-yellow-600 mb-4">The requested lead could not be found.</p>
          <Button onClick={() => router.push('/super-admin/insights')} variant="primary">
            Go Back
          </Button>
        </div>
      </DashboardLayout>
    );
  }

  return (
    <RouteGuard allowedRoles={['super_admin']}>
      <DashboardLayout 
        showBreadcrumb={true}
        breadcrumbVariant="elevated"
        breadcrumbSize="md"
      >
        <div className="space-y-6">

          {/* Header with actions */}
          <div className="flex justify-between items-center">
            <div className="flex items-center space-x-4">
              <div className="h-16 w-16 rounded-full bg-blue-100 flex items-center justify-center">
                <span className="text-2xl font-medium text-blue-600">
                  {lead.firstName.charAt(0)}{lead.lastName.charAt(0)}
                </span>
              </div>
              <div>
                <h1 className="text-2xl font-bold text-gray-900">{lead.firstName} {lead.lastName}</h1>
                <p className="text-gray-600">{lead.email}</p>
              </div>
            </div>
            <div className="flex space-x-3">
              <Button variant="primary">
                Edit Lead
              </Button>
            </div>
          </div>

          {/* Status badges */}
          <div className="flex space-x-4">
            <span className={`inline-flex items-center px-3 py-1 rounded-full text-sm font-medium ${getStatusColor(lead.status)}`}>
              {lead.status.charAt(0).toUpperCase() + lead.status.slice(1)}
            </span>
            <span className={`inline-flex items-center px-3 py-1 rounded-full text-sm font-medium ${getStageColor(lead.conversionStage)}`}>
              {lead.conversionStage.charAt(0).toUpperCase() + lead.conversionStage.slice(1)}
            </span>
            <span className={`inline-flex items-center px-3 py-1 rounded-full text-sm font-medium ${getPriorityColor(lead.priority)}`}>
              {lead.priority.charAt(0).toUpperCase() + lead.priority.slice(1)}
            </span>
          </div>

          {/* Main content grid */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Contact & Basic Information */}
            <div className="lg:col-span-2 space-y-6">
              <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Contact & Basic Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="text-sm font-medium text-gray-500">First Name</label>
                    <p className="text-gray-900">{lead.firstName}</p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500">Last Name</label>
                    <p className="text-gray-900">{lead.lastName}</p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500">Email</label>
                    <p className="text-gray-900">{lead.email}</p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500">Phone</label>
                    <p className="text-gray-900">{lead.phone}</p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500">Source</label>
                    <p className="text-gray-900">{lead.source?.replace('_', ' ').toUpperCase() || 'Unknown'}</p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500">Geographic Location</label>
                    <p className="text-gray-900">{lead.geographicLocation || 'N/A'}</p>
                  </div>
                </div>
              </div>

              {/* Financial Information */}
              <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Financial Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="text-sm font-medium text-gray-500">Loan Amount</label>
                    <p className="text-gray-900">{formatCurrency(lead.loanAmount)}</p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500">Credit Score</label>
                    <p className="text-gray-900">{lead.creditScore || 'N/A'}</p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500">Loan Amount Closed</label>
                    <p className="text-gray-900">{formatCurrency(lead.loanAmountClosed)}</p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500">Commission Earned</label>
                    <p className="text-gray-900">{formatCurrency(lead.commissionEarned)}</p>
                  </div>
                </div>
              </div>

              {/* Performance & Analytics */}
              <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Performance & Analytics</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="text-sm font-medium text-gray-500">Lead Quality Score</label>
                    <p className="text-gray-900">{lead.leadQualityScore || 'N/A'}</p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500">Response Time (Hours)</label>
                    <p className="text-gray-900">{lead.responseTimeHours || 'N/A'}</p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500">Contact Count</label>
                    <p className="text-gray-900">{lead.contactCount}</p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500">Last Contact Date</label>
                    <p className="text-gray-900">{lead.lastContactDate ? formatDate(lead.lastContactDate) : 'N/A'}</p>
                  </div>
                </div>
              </div>

              {/* Notes */}
              <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Notes</h3>
                <div className="bg-gray-50 rounded-md p-4 min-h-[100px]">
                  <p className="text-gray-700 whitespace-pre-wrap">{lead.notes || 'No notes available'}</p>
                </div>
              </div>
            </div>

            {/* Sidebar */}
            <div className="space-y-6">
              {/* Timeline */}
              <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Timeline</h3>
                <div className="space-y-4">
                  <div>
                    <label className="text-sm font-medium text-gray-500">Created</label>
                    <p className="text-gray-900">{formatDate(lead.createdAt)}</p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500">Last Updated</label>
                    <p className="text-gray-900">{formatDate(lead.updatedAt)}</p>
                  </div>
                </div>
              </div>

              {/* Quick Actions */}
              <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Quick Actions</h3>
                <div className="space-y-3">
                  <Button variant="primary" className="w-full">
                    Send Email
                  </Button>
                  <Button variant="outline-white" className="w-full">
                    Schedule Call
                  </Button>
                  <Button variant="outline-white" className="w-full">
                    Add Note
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </DashboardLayout>
    </RouteGuard>
  );
}
